### PR TITLE
fix(import): Parse boolean also from numbers - Issue #159

### LINKED ISSUE #159: XLSX reader translates FALSE into "0"
When importing data from XSLX file, it translates string "FALSE" into "0" which breaks boolean parser with this error: '[row 2:allg-sperrvermerk-2076-b-s] The value \'0\' isn\'t a valid boolean!'

File with this behavior can look for example like this [simple.xlsx](https://github.com/sphereio/sphere-node-product-csv-sync/files/770590/2rows-simple.xlsx)

### PR DESCRIPTION
**Pull request by junajan**
Fixes #159

### CODE REVIEW

File: src/coffee/mapping.coffee [hunk 1]
```diff
@@ -334,10 +334,11 @@ class Mapping
     errorMsg = "[row #{rowIndex}:#{attribName}] The value '#{rawBoolean}' isn't a valid boolean!"
     try
       b = JSON.parse(rawBoolean.toLowerCase())
-      if not _.isBoolean b
+      if _.isBoolean(b) or _.isNumber(b)
```
Comment (hisabimbola) [inline src/coffee/mapping.coffee]: why are we doing this??

Can you provide some context??

File: src/spec/mapping.spec.coffee [hunk 2]
```diff
@@ -631,6 +631,12 @@ describe 'Mapping', ->
     it 'should map true', ->
       expect(@map.mapBoolean('true')).toBe true
 
+    it 'should map true represented as a number', ->
```
Comment (hisabimbola) [inline src/spec/mapping.spec.coffee]: so does that make this -> `1234567` a Boolean??

File: src/coffee/mapping.coffee (hunk 1 above)
Comment (hisabimbola) [inline src/coffee/mapping.coffee]: Nevermind, I just read through the issue 😺

File: src/spec/mapping.spec.coffee (hunk 2 above)
Comment (junajan) [inline src/spec/mapping.spec.coffee]: Yes, this will be parsed as a `true`

Comment (hisabimbola) [inline src/spec/mapping.spec.coffee]: I am not sure `1234567` should pass a Boolean test.

Comment (Siilwyn) [inline src/spec/mapping.spec.coffee]: That's actually pretty weird yes. We could just test if it's a zero or a one.

Comment (junajan) [inline src/spec/mapping.spec.coffee]: Updated here f988a13 :sunny:

File: src/coffee/mapping.coffee [hunk 3]
```diff
@@ -334,7 +334,7 @@ class Mapping
     errorMsg = "[row #{rowIndex}:#{attribName}] The value '#{rawBoolean}' isn't a valid boolean!"
     try
       b = JSON.parse(rawBoolean.toLowerCase())
-      if _.isBoolean(b) or _.isNumber(b)
+      if _.isBoolean(b) or b == 0 or b == 1
```
Comment (hisabimbola) [inline src/coffee/mapping.coffee]: Are we expecting this to be a number or string because 

```js
Boolean(1) // - outputs true
Boolean('1') // - outputs true
Boolean(0) // - outputs false
Boolean('0') // - outputs true
```

File: src/spec/mapping.spec.coffee [hunk 4]
```diff
@@ -637,6 +637,11 @@ describe 'Mapping', ->
     it 'should map false represented as a number', ->
       expect(@map.mapBoolean('0')).toBe false
```
Comment (hisabimbola) [inline src/spec/mapping.spec.coffee]: I wonder how this tests pass 🤔

Comment (hisabimbola) [inline src/spec/mapping.spec.coffee]: Never mind, I see the `JSON.parse` line now.
