### PR TITLE
fix(reader): Fix reading of xlsx richtext

### LINKED ISSUE #187: [Excel import]: cell items imported as `[object Object]`
### Description

Cell items containing multiple styles in `.xlsx` files are not properly imported

### Expected Behavior

All/only text content of columns should be imported
### Current Behavior

Extra styling options are passed in, creating an object which is stringified to `[object Object]`

### PR DESCRIPTION
**Pull request by junajan**
#### Summary
Fixes #187

#### Description
This PR adds a stringify method for a richText object.

#### Todo

- Tests
    - [x] Unit
    - [ ] Integration
    - [ ] Acceptance
- [ ] Documentation

### CODE REVIEW

File: src/coffee/io/reader.coffee [hunk 1]
```diff
@@ -98,4 +102,10 @@ class Reader
     @Logger.debug "get header"
     @header
 
+  # method will remove styling from richText and return a plain text
+  _stringifyRichText: (richText) ->
```
Comment (wizzy25) [inline src/coffee/io/reader.coffee]: Why not reduce in this case? 
```js
_stringifyRichText: (richText) ->
  richText.reduce ((acc, chunk) ->
    chunk.text
  ), ''
```

Comment (junajan) [reply src/coffee/io/reader.coffee]: Updated c3b2293
