### PR TITLE
fix(sphere-node-product-csv-sync): Logging entries missing on product status during unpublish of products

### LINKED ISSUE #249: Logging entries missing on Product Status during unpublish of products
### Description
Perform the unpublish command on product state update with a large number of products (e.g. 41,000 products).

### Expected Behavior
Logging entries are completely displayed.

### Current Behavior
Logging entries stop being displayed at some point when a large number of products is involved.

```js
'[row 0] Product unpublished.',
'[row 0] Product unpublished.',
'[row 0] Product u
```

### Context
Unpublish a large number of products.

### PR DESCRIPTION
**Pull request by Babanila**
#### Summary
Fix  missing logging entries on product status during unpublish of products

#### Description
This PR fixes missing log entries output when unpublish a large number of products in `Product Status` on IMPEX.

#### Todo

- Tests
    - [x] Unit
    - [x] Integration

Closes #249

### CODE REVIEW

File: src/coffee/run.coffee [hunk 1]
```diff
@@ -213,6 +212,7 @@ module.exports = class
         .then (authConfig) =>
           options =
             timeout: program.timeout
+            exportFormat: 'txt'
```
Comment (Babanila) [inline src/coffee/run.coffee]: Add output file format.

File: src/coffee/run.coffee [hunk 2]
```diff
@@ -244,7 +244,10 @@ module.exports = class
               importer.continueOnProblems = opts.continueOnProblems
               importer.changeState(publish, remove, filterFunction)
             .then (result) ->
-              _consoleWarnAllResults result
+              if result.length > 500
```
Comment (Babanila) [inline src/coffee/run.coffee]: If the products are more than 500, it should write to a file.

File: src/coffee/run.coffee [hunk 3]
```diff
@@ -89,9 +89,7 @@ module.exports = class
   @run: (argv) ->
     
     _consoleWarnAllResults = (result) ->
-      # print out full response array by passing util.inspect
-      # with maxArrayLength (default is 100)
-      console.warn util.inspect(result, { maxArrayLength: null })
+      console.warn result
```
Comment (Babanila) [inline src/coffee/run.coffee]: Remove `util.inspect` because its output can 't be depended on ([see the link](https://nodejs.org/dist/latest-v10.x/docs/api/util.html#util_util_inspect_object_options)).

Comment (daern91) [reply src/coffee/run.coffee]: What do you mean with it cant be depended on?

File: src/coffee/run.coffee (hunk 1 above)
Comment (daern91) [reply src/coffee/run.coffee]: should this really be a `txt` file?

File: src/coffee/run.coffee [hunk 4]
```diff
@@ -203,6 +201,7 @@ module.exports = class
       .description 'Allows to publish, unpublish or delete (all) products of your SPHERE.IO project.'
       .option '--changeTo <publish,unpublish,delete>', 'publish unpublished products / unpublish published products / delete unpublished products'
       .option '--csv <file>', 'processes products defined in a CSV file by either "sku" or "id". Otherwise all products are processed.'
+      .option '-o, --output <file>', 'Path to the file the product\'s state will write the resulting output in only if the product is more than 500'
```
Comment (daern91) [inline src/coffee/run.coffee]: I dont really understand this sentence, could we please rewrite it?

File: src/coffee/run.coffee (hunk 2 above)
Comment (daern91) [reply src/coffee/run.coffee]: Interesting, does it crash at 500 logging outputs already?

Comment (Babanila) [reply src/coffee/run.coffee]: No, it doesn't.

File: src/coffee/run.coffee (hunk 3 above)
Comment (Babanila) [reply src/coffee/run.coffee]: From the Node docs, `Util.inspect` output can change anytime without public release or update and from the issues, it shows that `Util.inspect` is not doing what was expected or needed (to output all the result).

File: src/coffee/run.coffee (hunk 2 above)
Comment (daern91) [reply src/coffee/run.coffee]: okay, so what is the reason for putting the limit at 500 already? Does seem a bit low to me.

File: src/coffee/run.coffee (hunk 3 above)
Comment (daern91) [reply src/coffee/run.coffee]: Okay, but if the default is `100` then this change means that we will not show anything between entry `101` and `500`, right?

File: src/coffee/run.coffee (hunk 4 above)
Comment (Babanila) [reply src/coffee/run.coffee]: That's just specified the output path where to write the result to.

File: src/coffee/run.coffee (hunk 2 above)
Comment (Babanila) [reply src/coffee/run.coffee]: It will only output 100.

File: src/coffee/run.coffee (hunk 1 above)
Comment (Babanila) [reply src/coffee/run.coffee]: I chose a `txt` file extension because it's a log file.

File: src/coffee/run.coffee (hunk 3 above)
Comment (Babanila) [reply src/coffee/run.coffee]: Yes.

File: src/coffee/run.coffee (hunk 1 above)
Comment (daern91) [reply src/coffee/run.coffee]: shouldn't it be a `log` file, then?

File: src/coffee/run.coffee [hunk 5]
```diff
@@ -213,6 +212,7 @@ module.exports = class
         .then (authConfig) =>
           options =
             timeout: program.timeout
+            exportFormat: 'log'
```
Comment (daern91) [inline src/coffee/run.coffee]: I cant see where this variable is actually used?

File: src/coffee/run.coffee (hunk 3 above)
Comment (daern91) [reply src/coffee/run.coffee]: Ok, I understand and this looks very dangerous to me. I looked at the git history and found [this PR](https://github.com/sphereio/sphere-node-product-csv-sync/pull/227) which introduced the change to using `util.inspect`.

The `_consoleWarnAllResults` seems to also be used in these places [1](https://github.com/sphereio/sphere-node-product-csv-sync/blob/faa1eead968e3f4d11c3c7c6b744becb1e8cdbd9/src/coffee/run.coffee#L187), [2](https://github.com/sphereio/sphere-node-product-csv-sync/blob/faa1eead968e3f4d11c3c7c6b744becb1e8cdbd9/src/coffee/run.coffee#L352), and [3](https://github.com/sphereio/sphere-node-product-csv-sync/blob/faa1eead968e3f4d11c3c7c6b744becb1e8cdbd9/src/coffee/run.coffee#L401). 

As the PR has not introduced an output `log file` for those commands, that means we will not output all the logging results for them. 

Seems a safer bet to me to keep `util.inspect()` here. The other alternative would be to also save outputted result logs to files in the three other commands.

Does it make sense? WDYT?

File: src/coffee/run.coffee [hunk 6]
```diff
@@ -244,7 +244,10 @@ module.exports = class
               importer.continueOnProblems = opts.continueOnProblems
               importer.changeState(publish, remove, filterFunction)
             .then (result) ->
-              _consoleWarnAllResults result
+              if result.length > 100
+                fs.writeFileSync opts.output, JSON.stringify(result, null, 2)
```
[the remark this answers is not in the document]
Comment (Babanila) [reply src/coffee/run.coffee]: It will throw an error.

File: src/coffee/run.coffee (hunk 5 above)
Comment (Babanila) [reply src/coffee/run.coffee]: Not used, will remove it.

File: src/coffee/run.coffee (hunk 6 above)
[the remark this answers is not in the document]
Comment (daern91) [reply src/coffee/run.coffee]: Ok, how about making sure this condition also checks if we have added the `-o` flag? Otherwise, this looks like a breaking change since it can cause new unexpected errors.

File: src/coffee/run.coffee (hunk 3 above)
Comment (Babanila) [reply src/coffee/run.coffee]: Sure, it's okay for now to avoid breaking the other modules that use the `_consoleWarnResults` but in future, it will be better to avoid the `Util.inspect()`.

File: src/coffee/run.coffee [hunk 7]
```diff
@@ -203,6 +203,7 @@ module.exports = class
       .description 'Allows to publish, unpublish or delete (all) products of your SPHERE.IO project.'
       .option '--changeTo <publish,unpublish,delete>', 'publish unpublished products / unpublish published products / delete unpublished products'
       .option '--csv <file>', 'processes products defined in a CSV file by either "sku" or "id". Otherwise all products are processed.'
+      .option '-o, --output <file>', 'Path to the file if the product being process is more than the default which is 100.'
```
Comment (daern91) [inline src/coffee/run.coffee]: I think this is still not clear. How about something like

`Optional path to results log output if it is larger than X`

File: src/coffee/run.coffee [hunk 8]
```diff
@@ -203,6 +203,7 @@ module.exports = class
...
       .option '--continueOnProblems', 'When a there is a problem on changing a product\'s state (400er response), ignore it and continue with the next products'
       .option '--forceDelete', 'whether to force deletion without asking for confirmation', false
       .usage '--projectKey <project-key> --clientId <client-id> --clientSecret <client-secret> --changeTo <state>'
```
Comment (daern91) [inline src/coffee/run.coffee]: since `-o` is now optional we don't need to add it to the example here :)

File: src/coffee/run.coffee (hunk 6 above)
[the remark this answers is not in the document]
Comment (daern91) [reply src/coffee/run.coffee]: Cool, thanks for adding the condition. Maybe we could then also increase the limit? Impex should be able to show 100 without any problems I think?

[the remark this answers is not in the document]
Comment (Babanila) [reply src/coffee/run.coffee]: I will suggest to leave it at default for this repo so that when `Util.inspect()` is removed in the future only the two remaining modules will need to be fixed.

[the remark this answers is not in the document]
Comment (daern91) [reply src/coffee/run.coffee]: I still don't see a reason to why we want to remove `Util.inspect()` though? Could you please elaborate to why you want to make that change? 

I read the link you posted above and only saw this

>The util.inspect() method returns a string representation of object that is intended for debugging. The output of util.inspect may change at any time and should not be depended upon programmatically. 

Since we are only passing this string to `console.warn` and use it for debugging and logging the results of the app it should be fine to keep it. 

In other words, we don't depend on the output in any other way in the app as we just log it out.

Maybe I'm missing something, please let me know.

[the remark this answers is not in the document]
Comment (Babanila) [reply src/coffee/run.coffee]: I think we should avoid `Util.inspect()` because it doesn't provide a permanent solution to the problem of logging.

It solved the problem when it was implemented then and now the same logging problem arise and since it was stated in the `Node docs` that `SHOULD NOT BE DEPENDED ON PROGRAMMATICALLY` and  we are using in IMPEX(production) for logging, my suggestion would be to avoid it and find a permanent solution or alternatives.

[the remark this answers is not in the document]
Comment (daern91) [reply src/coffee/run.coffee]: I see your point but I think you missed my line above.

> In other words, we don't depend on the output in any other way in the app as we just log it out.

In fact, even `console.warn` itself uses `util.inspect()`([ref](https://nodejs.org/api/console.html#console_console_error_data_args)).

You could even test it out yourself by setting the default option to it [like this](https://nodejs.org/api/util.html#util_util_inspect_defaultoptions) then only calling `console.warn`. It will have exactly the same effect.

File: src/coffee/run.coffee (hunk 8 above)
Comment (Babanila) [reply src/coffee/run.coffee]: For documentation purpose, it will be better to have it written down as part of the option available for `command-line usage` in the module. I'll modify the sentence to inform the user that it is an optional parameter.
