### PR TITLE
Fix exporting of template due to missing credentials

### LINKED ISSUE #245: Template subcommand does not accept project config via parameters
### Description
Module was installed via _npm install sphere-node-product-csv-sync_.
Running the template subcommand requires the project auth config to be given (project key, project client id, client secret), but they are never actually used.

### Expected Behavior
Running 
```
product-csv-sync template --projectKey <project-key> --clientId <client-id> --clientSecret <client-secret> --out <file>
```
generates a template file for export.

### Current Behavior
The error
```
Problems on getting client credentials from config files: Error: No project defined. Please enter a project key
```
is returned upon running the subcommand.

### Possible Solution
In src/coffee/export.coffee on line 322, @projectKey should also be passed to the getAll function. 

Additionally - thought this may be a peculiarity of my own sphere project - on line 324, just productTypes should only be assigned "result", not "result.body.results".

### PR DESCRIPTION
**Pull request by wirtsi**
#### Summary
Fixes #245

#### Description
The template command fails to pull in the project-key.
Tests pass when adding a config.js file, not sure what to reference there

### CODE REVIEW

File: src/coffee/export.coffee [hunk 1]
```diff
@@ -321,9 +321,9 @@ class Export
           Promise.reject err
 
   createTemplate: (languages, outputFile, allProductTypes = false) ->
-    @typesService.getAll(@client)
+    @typesService.getAll(@client, @projectKey)
     .then (result) =>
-      productTypes = result.body.results
+      productTypes = result
```
Comment (junajan) [inline src/coffee/export.coffee]: Hi @wirtsi .. why not naming it `productTypes`  right away one line above?

Comment (wirtsi) [reply src/coffee/export.coffee]: Right, I changed this ....
