### PR TITLE
fix(mapping): fix mapping of prefixed attributes

### LINKED ISSUE #236: Localisation attribute named as attribute.description is not being imported
### Support reference number
SUPPORT-4407

### Description
There is a problem when importing attributes prefixed with `attribute.` string. Currently they are ignored

### PR DESCRIPTION
**Pull request by junajan**
#### Summary
Fixes #236

#### Description
Specify the whole list of attribute names which are being prefixed by the exporter.

#### Todo

- Tests
    - [x] Unit
    - [ ] Integration
    - [ ] Acceptance
- [ ] Documentation

### CODE REVIEW

File: src/coffee/constants.coffee [hunk 1]
```diff
@@ -81,4 +81,31 @@ exports.SPECIAL_HEADERS = [
...
+  'createdAt',
+  'lastModifiedAt',
+  'categories',
+  'hasStagedChanges',
+  'published',
+  'masterVariant',
+  'variants',
+  'taxCategory',
+  'reviewRatingStatistics'
+]
```
Comment (daern91) [inline src/coffee/constants.coffee]: LGTM, could we please also add that link to where to find these? Just to make sure it's easy to keep everything up-to-date if/when needed.

Comment (junajan) [reply src/coffee/constants.coffee]: Hello @daern91 .. I added a comment here a0782a2
